const mongoose = require("mongoose");
const { ObjectId } = mongoose.Schema;

const productSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      trim: true,
      required: true,
      maxlength: 32,
      text: true,
    },
    slug: {
      type: String,
      unique: true,
      lowercase: true,
      index: true,
    },
    description: {
      type: String,
      required: true,
      maxlength: 2000,
      text: true,
    },
    price: {
      type: Number,
      required: true,
      trim: true,
      maxlength: 32,
    },
    gst: {
      type: String,
      required: true,
    },
    category: {
      type: ObjectId,
      ref: "Category",
    },
    subs: [
      {
        type: ObjectId,
        ref: "Sub",
      },
    ],
    quantity: {
      type: Number,
    },
    sold: {
      type: Number,
      default: 0,
    },
    images: {
      type: Array,
    },
    shipping: {
      type: String,
      enum: ["Yes", "No"],
    },
    color: {
      type: String,
      // enum: [
      //   "AliceBlue",
      //   "AntiqueWhite",
      //   "Aqua",
      //   "Aquamarine",
      //   "Azure",
      //   "Beige",
      //   "Bisque",
      //   "Black",
      //   "BlanchedAlmond",
      //   "Blue",
      //   "BlueViolet",
      //   "Brown",
      //   "BurlyWood",
      //   "CadetBlue",
      //   "Chartreuse",
      //   "Chocolate",
      //   "Coral",
      //   "CornflowerBlue",
      //   "Cornsilk",
      //   "Crimson",
      //   "Cyan",
      //   "DarkBlue",
      //   "DarkCyan",
      //   "DarkGoldenRod",
      //   "DarkGray",
      //   "DarkGrey",
      //   "DarkGreen",
      //   "DarkKhaki",
      //   "DarkMagenta",
      //   "DarkOliveGreen",
      //   "DarkOrange",
      //   "DarkOrchid",
      //   "DarkRed",
      //   "DarkSalmon",
      //   "DarkSeaGreen",
      //   "DarkSlateBlue",
      //   "DarkSlateGray",
      //   "DarkSlateGrey",
      //   "DarkTurquoise",
      //   "DarkViolet",
      //   "DeepPink",
      //   "DeepSkyBlue",
      //   "DimGray",
      //   "DimGrey",
      //   "DodgerBlue",
      //   "FireBrick",
      //   "FloralWhite",
      //   "ForestGreen",
      //   "Fuchsia",
      //   "Gainsboro",
      //   "GhostWhite",
      //   "Gold",
      //   "GoldenRod",
      //   "Gray",
      //   "Grey",
      //   "Green",
      //   "GreenYellow",
      //   "HoneyDew",
      //   "HotPink",
      //   "IndianRed",
      //   "Indigo",
      //   "Ivory",
      //   "Khaki",
      //   "Lavender",
      //   "LavenderBlush",
      //   "LawnGreen",
      //   "LemonChiffon",
      //   "LightBlue",
      //   "LightCoral",
      //   "LightCyan",
      //   "LightGoldenRodYellow",
      //   "LightGray",
      //   "LightGrey",
      //   "LightGreen",
      //   "LightPink",
      //   "LightSalmon",
      //   "LightSeaGreen",
      //   "LightSkyBlue",
      //   "LightSlateGray",
      //   "LightSlateGrey",
      //   "LightSteelBlue",
      //   "LightYellow",
      //   "Lime",
      //   "LimeGreen",
      //   "Linen",
      //   "Magenta",
      //   "Maroon",
      //   "MediumAquaMarine",
      //   "MediumBlue",
      //   "MediumOrchid",
      //   "MediumPurple",
      //   "MediumSeaGreen",
      //   "MediumSlateBlue",
      //   "MediumSpringGreen",
      //   "MediumTurquoise",
      //   "MediumVioletRed",
      //   "MidnightBlue",
      //   "MintCream",
      //   "MistyRose",
      //   "Moccasin",
      //   "NavajoWhite",
      //   "Navy",
      //   "OldLace",
      //   "Olive",
      //   "OliveDrab",
      //   "Orange",
      //   "OrangeRed",
      //   "Orchid",
      //   "PaleGoldenRod",
      //   "PaleGreen",
      //   "PaleTurquoise",
      //   "PaleVioletRed",
      //   "PapayaWhip",
      //   "PeachPuff",
      //   "Peru",
      //   "Pink",
      //   "Plum",
      //   "PowderBlue",
      //   "Purple",
      //   "RebeccaPurple",
      //   "Red",
      //   "RosyBrown",
      //   "RoyalBlue",
      //   "SaddleBrown",
      //   "Salmon",
      //   "SandyBrown",
      //   "SeaGreen",
      //   "SeaShell",
      //   "Sienna",
      //   "Silver",
      //   "SkyBlue",
      //   "SlateBlue",
      //   "SlateGray",
      //   "SlateGrey",
      //   "Snow",
      //   "SpringGreen",
      //   "SteelBlue",
      //   "Tan",
      //   "Teal",
      //   "Thistle",
      //   "Tomato",
      //   "Turquoise",
      //   "Violet",
      //   "Wheat",
      //   "White",
      //   "WhiteSmoke",
      //   "Yellow",
      //   "YellowGreen",
      // ],
    },
    brand: {
      type: String,
    },
    material: {
      type: String,
    },
    property: {
      type: String,
    },
    design: {
      type: String,
    },
    style: {
      type: String,
    },
    application: {
      type: String,
    },
    instruction: {},
    width: {
      type: Number,
    },
    length: {
      type: Number,
    },
    weight: {
      type: Number,
    },
    repeatLength: {
      type: Number,
    },
    rollLength: {
      type: Number,
    },
    ratings: [
      {
        star: Number,
        postedBy: { type: ObjectId, ref: "User" },
      },
    ],
  },
  { timestamps: true }
);

module.exports = mongoose.model("Product", productSchema);
